### ISSUE TITLE
Add .atomignore_global support

### ISSUE THREAD

**Issue by abdonrd** [leny/atom-tree-ignore#6]
Add .atomignore_global support, like the .gitignore_global.

**Comment by leny** [comment]
Hi, thanks for the idea.

I'm currently quite busy (end of school year, exams and presentations to correct for my students), so, don't hesitate to submit a Pull Request for this feature!

**Comment by PhiLhoSoft** [comment]
I see two issues with this request:
- Where should this file go? Would need to add a setting to get its path, perhaps.
- It duplicates the **Ignored Names** setting in Atom: atom-tree-ignore was made to apply this feature on project basis, adding a global setting would go back to original feature!

**Comment by timkelty** [comment]
+1 for this!

@PhiLhoSoft:

> Where should this file go?

I would expect it to be in your user home directory, much like `~/.gitignore_global`

> It duplicates the Ignored Names setting in Atom

Here are the key differences for me:
- I use `atom-tree-ignore` because I still want to be able to fuzzy find those items. **Ignored Names** removes them from that search.
- Also, with `atom-tree-ignore` I'm able to easily toggle, with Atom's **Ignored Names**, I cannot.

**Comment by abdonrd** [comment]
Closing very old issue...
