### ISSUE TITLE
Exclude file/directory

### ISSUE THREAD

**Issue by mbrammer** [leny/atom-tree-ignore#8]
You write the .atomignore is working like the .gitignore, but when I add something like this:

```
libraries
!libraries/libtoshow
```

`libraries/libtoshow` should be visible and all other files/directories in `libraries` should be hidden.

**Comment by leny** [comment]
Hi, thanks for the report.

I'm currently quite busy with professional work, so, if you feel to submit a Pull Request, be my guest ;)

**Comment by PhiLhoSoft** [comment]
This one is not easy, because of the way the package works: it takes each path of the tree-view, from top to bottom, and just feed them to the `ignore` library that checks against the `.gitignore` rules. If filtered out, it just adds a style to the tree item that hides it (and its descendants).

So, if one sub-item is not hidden, it should walk up the tree items and unhide them...

Note: because of another bug, there is actually a workaround!
Ignore `library/` instead of just `library`...

**Comment by leny** [comment]
You're totally right. I'm thinking about how to fix this without the need of _too much_ code, but it will not be really practical to do.

**Comment by PhiLhoSoft** [comment]
It is more complex than that, because when a folder is closed (children not visible), the children are not in the Dom, therefore their paths won't be in the list to be processed by `ignore`. So the parent folder will be hidden and there will be no possibility to open it to see the not-hidden files...

It probably needs an analysis of the `.atomignore` file for these cases...

**Comment by leny** [comment]
I think the right process is to look onto the tree-view package to see how they done it for the .gitignore files.
Will take a look when I got time.

**Comment by PhiLhoSoft** [comment]
The more I think of it, the more I believe it might be the responsibility of the `ignore` library to manage these cases... Like if a `!foo/bar` is detected, `foo/` should not be ignored. Since `foo/` is a folder, it makes sense anyway (git only manage files).
I will investigate a bit more (re-read .gitignore rules, see the code of the library, its unit tests, etc.), and if it makes sense, I will open an issue in this library.
